import { createContext, useContext, useState, type KeyboardEvent, type ReactNode } from "react";
import { cn } from "@/shared/utils/cn";

// ==========================================================================
// Types
// ==========================================================================

interface AccordionContextType {
  /** The currently-expanded item ID, or null if all are collapsed. */
  activeId: string | null;
  setActiveId: (id: string | null) => void;
  /** Stable base ID generated by Root for unique ARIA IDs. */
  baseId: string;
}

interface AccordionItemContextType {
  itemId: string;
}

// ==========================================================================
// Contexts
// ==========================================================================

let _idCounter = 0;
/**
 * Stable but simple unique-ID generator. We avoid `useId()` here because it
 * produces different values between server and client renders, which causes
 * hydration mismatches in non-SSR scenarios common at this stage.
 */
function useStableId(): string {
  const [id] = useState(() => `accordion-${++_idCounter}`);
  return id;
}

const AccordionContext = createContext<AccordionContextType | null>(null);
const AccordionItemContext = createContext<AccordionItemContextType | null>(null);

function useAccordionContext(): AccordionContextType {
  const ctx = useContext(AccordionContext);
  if (!ctx) {
    throw new Error("Accordion sub-components must be used within <Accordion.Root>");
  }
  return ctx;
}

function useAccordionItemContext(): AccordionItemContextType {
  const ctx = useContext(AccordionItemContext);
  if (!ctx) {
    throw new Error("Accordion sub-components must be used within <Accordion.Item>");
  }
  return ctx;
}

// ==========================================================================
// Sub-components
// ==========================================================================

// ---- Root ----------------------------------------------------------------

interface RootProps {
  children: ReactNode;
  /** The item ID that should be open by default. */
  defaultOpen?: string;
  className?: string;
}

function Root({ children, defaultOpen, className }: RootProps) {
  const [activeId, setActiveId] = useState<string | null>(defaultOpen ?? null);
  const baseId = useStableId();

  return (
    <AccordionContext.Provider value={{ activeId, setActiveId, baseId }}>
      <div className={cn("divide-y divide-border", className)}>
        {children}
      </div>
    </AccordionContext.Provider>
  );
}

// ---- Item ----------------------------------------------------------------

interface ItemProps {
  children: ReactNode;
  /** Unique identifier for this accordion item. */
  id: string;
  className?: string;
}

function Item({ children, id, className }: ItemProps) {
  return (
    <AccordionItemContext.Provider value={{ itemId: id }}>
      <div className={cn(className)}>
        {children}
      </div>
    </AccordionItemContext.Provider>
  );
}

// ---- Trigger -------------------------------------------------------------

interface TriggerProps {
  children: ReactNode;
  className?: string;
}

function Trigger({ children, className }: TriggerProps) {
  const { activeId, setActiveId, baseId } = useAccordionContext();
  const { itemId } = useAccordionItemContext();

  const isOpen = activeId === itemId;
  const contentId = `${baseId}-${itemId}-content`;
  const triggerId = `${baseId}-${itemId}-trigger`;

  function toggle() {
    setActiveId(isOpen ? null : itemId);
  }

  function handleKeyDown(e: KeyboardEvent<HTMLButtonElement>) {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      toggle();
    }
  }

  return (
    <button
      id={triggerId}
      type="button"
      aria-expanded={isOpen}
      aria-controls={contentId}
      onClick={toggle}
      onKeyDown={handleKeyDown}
      className={cn(
        "flex w-full items-center justify-between px-4 py-3 text-left text-sm font-medium text-text-primary transition-colors hover:bg-accent-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary",
        className,
      )}
    >
      {children}
      <Chevron isOpen={isOpen} />
    </button>
  );
}

// ---- Content -------------------------------------------------------------

interface ContentProps {
  children: ReactNode;
  className?: string;
}

function Content({ children, className }: ContentProps) {
  const { activeId, baseId } = useAccordionContext();
  const { itemId } = useAccordionItemContext();

  const isOpen = activeId === itemId;
  const contentId = `${baseId}-${itemId}-content`;
  const triggerId = `${baseId}-${itemId}-trigger`;

  return (
    <div className={cn("overflow-hidden", className)}>
    <div
      id={contentId}
      role="region"
      aria-labelledby={triggerId}
      className={cn("overflow-hidden", className)}
      style={{
        display: "grid",
        gridTemplateRows: isOpen ? "1fr" : "0fr",
        transition: "grid-template-rows 200ms ease-out",
      }}
    >
      <div>
        {children}
      </div>
    </div>
    </div>
  );
}

// ---- Chevron icon (internal) ---------------------------------------------

function Chevron({ isOpen }: { isOpen: boolean }) {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
      className={cn(
        "text-text-secondary transition-transform duration-200",
        isOpen && "rotate-180",
      )}
    >
      <path
        d="M4 6l4 4 4-4"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

// ==========================================================================
// Compound export
// ==========================================================================

const AccordionBase = { Root, Item, Trigger, Content };

type AccordionType = {
  Root: typeof Root;
  Item: typeof Item;
  Trigger: typeof Trigger;
  Content: typeof Content;
};

export const Accordion = AccordionBase as AccordionType;
